swagger: '2.0'
info:
  description: |
    VMware Serverles - API Manager APIs
  version: 1.0.0
  title: API Manager
  contact:
    email: xueyangh@vmware.com
tags:
- name: api
  description: CRUD operations on APIs
schemes:
- http
- https
basePath: /v1/api
paths:
  /:
    post:
      tags:
      - api
      summary: Add a new API
      operationId: addAPI
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: API object
        required: true
        schema:
          $ref: '#/definitions/API'
      responses:
        200:
          description: API created
          schema:
            $ref: '#/definitions/API'
        400:
          description: Invalid Input
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized Request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Error
          schema:
            $ref: '#/definitions/Error'
    get:
      tags:
      - api
      summary: List all existing APIs
      operationId: getAPIs
      produces:
      - application/json
      parameters:
      # TODO: more parameters?
      - in: query
        type: string
        name: function
        description: Filter based on function names
      - in: query
        type: array
        name: tags
        description: Filter on API tags
        items:
          type: string
        collectionFormat: 'multi'
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/API'
        500:
          description: Internal Error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /{api}:
    parameters:
    - in: path
      name: api
      description: Name of API to work on
      required: true
      type: string
      pattern: '^[\w\d\-]+$'
    get:
      tags:
      - api
      summary: Find API by name
      description: get an API by name
      operationId: getAPI
      produces:
      - application/json
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/API'
        400:
          description: Invalid Name supplied
          schema:
            $ref: '#/definitions/Error'
        404:
          description: API not found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
    put:
      tags:
      - api
      summary: Update an API
      operationId: updateAPI
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: API object
        required: true
        schema:
          $ref: '#/definitions/API'
      responses:
        200:
          description: Successful update
          schema:
            $ref: '#/definitions/API'
        400:
          description: Invalid input
          schema:
            $ref: '#/definitions/Error'
        404:
          description: API not found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags:
      - api
      summary: Deletes an API
      operationId: deleteAPI
      produces:
      - application/json
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/API'
        400:
          description: Invalid Name supplied
          schema:
            $ref: '#/definitions/Error'
        404:
          description: API not found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'

security:
  - cookie: []
securityDefinitions:
  cookie:
    type: apiKey
    description: use cookies for authentication, when the user already logged in
    in: header
    name: Cookie
definitions:
  Tag:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  API:
    type: object
    required:
    - name
    - function
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
        pattern: '^[\w\d\-]+$'
      function:
        type: string
        description: the name of the function associated with
      methods:
        type: string
        description: a comma-separate list of HTTP methods that point to the API
      uris:
        type: string
        description: a comma-separate list of URIs prefixes that point to the API
      hosts:
        type: string
        description: a comma-separate list of domain names that point to the API
      enabled:
        type: boolean
        description: a easy way to disable an API without deleting it.
      authentication:
        type: string
        description: the authentication method for api consumers (public, basic, oidc, etc.)
      enable-tls:
        type: boolean
        description: enables tls, the tls credentials should also be set
      tls:
        type: string
        description: the tls credentials (imported from serverless secret) for https connection
      https-only:
        type: boolean
        description: only serves this API through HTTPS
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
