swagger: '2.0'
info:
  description: |
    This is the API server for the serverless image manager service.
  version: 1.0.0
  title: Image Manager
  contact:
    email: bjung@vmware.com
tags:
- name: baseImage
  description: Operations on base-images
- name: image
  description: Operations on images
- name: systemPackage
  description: Operations on system packages
- name: runtimePackage
  description: Operations on runtime packages
schemes:
- http
basePath: /v1/image
paths:
  /base:
    post:
      tags:
      - baseImage
      summary: Add a new base image
      operationId: addBaseImage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Base image object
        required: true
        schema:
          $ref: '#/definitions/BaseImage'
      responses:
        201:
          description: created
          schema:
            $ref: '#/definitions/BaseImage'
        400:
          description: Invalid input
    get:
      tags:
      - baseImage
      summary: List all existing base images
      operationId: getBaseImages
      produces:
      - application/json
      parameters:
      - in: query
        name: runtime
        description: Base image runtime/language
        type: string
      - in: query
        name: tags
        description: Filter on base image tags
        type: array
        items:
          type: string
        collectionFormat: 'multi'
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/BaseImage'
  /base/{baseImageID}:
    parameters:
    - in: path
      name: baseImageID
      description: ID of base image to return
      required: true
      type: string
      format: uuid
    get:
      tags:
      - baseImage
      summary: Find base image by ID
      description: Returns a single base image
      operationId: getBaseImageById
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/BaseImage'
        400:
          description: Invalid ID supplied
        404:
          description: Base image not found
    put:
      tags:
      - baseImage
      summary: Updates a base image
      operationId: updateBaseImageById
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/BaseImage'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/BaseImage'
        400:
          description: Invalid input
        404:
          description: Image not found
    delete:
      tags:
      - baseImage
      summary: Deletes a base image
      operationId: deleteBaseImageById
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/BaseImage'
        400:
          description: Invalid ID supplied
        404:
          description: Base image not found
  /:
    get:
      tags:
      - image
      summary: Get all images
      description: List all images
      operationId: getImages
      produces:
      - application/json
      parameters:
      - in: query
        name: language
        description: image runtime language
        type: string
      - in: query
        name: tags
        description: Filter on image tags
        type: array
        items:
          type: string
        collectionFormat: 'multi'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Image'
    post:
      tags:
      - image
      summary: Add a new image
      operationId: addImage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Image object
        required: true
        schema:
          $ref: '#/definitions/Image'
      responses:
        201:
          description: created
          schema:
            $ref: '#/definitions/Image'
        400:
          description: Invalid input
  /{imageID}:
    parameters:
    - in: path
      name: imageID
      description: ID of base image to return
      required: true
      type: string
      format: uuid
    get:
      tags:
      - image
      summary: Find image by ID
      description: Returns a single image
      operationId: getImageById
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Image'
        400:
          description: Invalid ID supplied
        404:
          description: Image not found
    put:
      tags:
      - image
      summary: Updates an image
      operationId: updateImageById
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/Image'
      responses:
        200:
          description: updated
          schema:
            $ref: '#/definitions/BaseImage'
        400:
          description: Invalid input
        404:
          description: Image not found
    delete:
      tags:
      - image
      summary: Deletes an image
      operationId: deleteImageById
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Image'
        400:
          description: Invalid ID supplied
        404:
          description: Image not found
definitions:
  Tag:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  Spec:
    type: string
    enum:
    - CONFIGURE
    - CREATE
    - DELETE
  Status:
    type: string
    enum:
    - INITIALIZED
    - CREATING
    - READY
    - ERROR
    - DELETED
  Language:
    type: string
    enum:
    - python2
    - python3
    - nodejs6
  BaseImage:
    type: object
    required:
    - name
    - dockerUrl
    - language
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      dockerUrl:
        type: string
      language:
        $ref: '#/definitions/Language'
      public:
        type: boolean
        default: false
      spec:
        $ref: '#/definitions/Spec'
      status:
        $ref: '#/definitions/Status'
      groups:
        type: array
        items:
          type: string
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
      createdTime:
        type: integer
  Image:
    type: object
    required:
    - name
    - baseImageID
    - language
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      baseImageID:
        type: string
        format: uuid
      language:
        $ref: '#/definitions/Language'
      spec:
        $ref: '#/definitions/Spec'
      status:
        $ref: '#/definitions/Status'
      groups:
        type: array
        items:
          type: string
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
      createdTime:
        type: integer