apiVersion: v1
kind: Service
metadata:
  name: image-manager
  namespace: default
  labels:
    name: image-manager
spec:
  selector:
    app: image-manager
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort