apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: function-manager-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: function-manager
    spec:
      containers:
      - name: function-manager
        image: berndtj/function-manager:latest
        imagePullPolicy: Always
        args: ["--config=/data/config/serverless.json", "--organization=$(ORGANIZATION)", "--host=0.0.0.0", "--port=8000", "--db-file=/data/function-manager/db.bolt", "--image-manager=image-manager:8000"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /data/function-manager
          name: function-manager
        - mountPath: /data/config
          name: serverless-config
          readOnly: true
        env:
        - name: ORGANIZATION
          valueFrom:
            configMapKeyRef:
              name: serverless
              key: organization
      volumes:
      - name: function-manager
        emptyDir: {}
      - name: serverless-config
        configMap:
          name: serverless
          items:
          - key: serverless.json
            path: serverless.json