apiVersion: v1
kind: Service
metadata:
  name: function-manager
  namespace: default
  labels:
    name: function-manager
spec:
  selector:
    app: function-manager
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort